#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Domotica.Resource", IsApplication=true)]

namespace Domotica
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050008
			public const int buttonC = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int buttonC_1 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int buttonChangePinState = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int buttonChangePinState2 = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int buttonChangePinState3 = 2131034126;
			
			// aapt resource value: 0x7f050007
			public const int buttonConnect = 2131034119;
			
			// aapt resource value: 0x7f05001b
			public const int count = 2131034139;
			
			// aapt resource value: 0x7f050017
			public const int countvalue = 2131034135;
			
			// aapt resource value: 0x7f050005
			public const int editTextIPAddress = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int editTextIPPort = 2131034118;
			
			// aapt resource value: 0x7f050013
			public const int lightSwitch = 2131034131;
			
			// aapt resource value: 0x7f050016
			public const int lightvalue = 2131034134;
			
			// aapt resource value: 0x7f050000
			public const int relativeLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050010
			public const int relativeLayout2 = 2131034128;
			
			// aapt resource value: 0x7f05001a
			public const int smlight = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int smtemp = 2131034137;
			
			// aapt resource value: 0x7f050011
			public const int tempSwitch = 2131034129;
			
			// aapt resource value: 0x7f050015
			public const int tempvalue = 2131034133;
			
			// aapt resource value: 0x7f05000b
			public const int textViewChangePinStateValue = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int textViewChangePinStateValue2 = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int textViewChangePinStateValue3 = 2131034127;
			
			// aapt resource value: 0x7f050003
			public const int textViewIPAddress = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int textViewIPPort = 2131034116;
			
			// aapt resource value: 0x7f050018
			public const int textViewSeconds = 2131034136;
			
			// aapt resource value: 0x7f050012
			public const int textViewSensorValue = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int textViewSensorValueb = 2131034132;
			
			// aapt resource value: 0x7f050001
			public const int textViewServer = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int textViewServerConnect = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040013
			public const int abort = 2130968595;
			
			// aapt resource value: 0x7f040000
			public const int application_name = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int arduino_server_connect = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int arduino_server_text = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int button_connect_text = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int button_pin_state_text = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int change_pin_state_value = 2130968588;
			
			// aapt resource value: 0x7f040010
			public const int debug_text = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int debug_value = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int exit = 2130968594;
			
			// aapt resource value: 0x7f040005
			public const int ip_address_text = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int ip_address_value = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int ip_port_text = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int ip_port_value = 2130968584;
			
			// aapt resource value: 0x7f04000b
			public const int pin_state_text = 2130968587;
			
			// aapt resource value: 0x7f04000d
			public const int sensor_text = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int sensor_value = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int sensor_valueb = 2130968591;
			
			// aapt resource value: 0x7f040001
			public const int timer_state_text = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int timer_state_value = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
